import Footer from "@/components/footer/Footer";
import Header from "@/components/sections/landing/header/Header";
import { appName } from "@/lib/app-name";

export const metadata = {
  title: appName + " | Buyer",
  description: "Generated by create next app",
};

const LandingLayout = ({ children }) => {
  return (
    <div className="flex w-full flex-col items-center">
      <Header />
      {children}
      <Footer />
    </div>
  );
};

export default LandingLayout;
