import Footer from "@/components/footer/Footer";
import Header from "@/components/sections/landing/header/Header";
import { appName } from "@/lib/app-name";
import { ChatStoreProvider } from "@/providers/chat-store-provider";
import { getUserProfile } from "@/lib/api/profile/getProfile";
import { ProfileStoreProvider } from "@/providers/profile-store-provider";

export const metadata = {
  title: appName + " | Buyer",
  description: "Generated by create next app",
};

const LandingLayout = async ({ children }) => {
  const profileRes = await getUserProfile();
  const profile = profileRes?.success ? profileRes : null;
  return (
    <div className="flex w-full flex-col items-center">
      <Header />
      <ProfileStoreProvider profile={profile}>
        <ChatStoreProvider>
          {children}
        </ChatStoreProvider>
      </ProfileStoreProvider>
      <Footer />
    </div>
  );
};

export default LandingLayout;
