import { Poppins } from "next/font/google";
import "./globals.css";
import { appName } from "@/lib/app-name";
import { Toaster } from "react-hot-toast";
import { NotificationProvider } from "@/providers/notification-provider";
import { NotificationStoreProvider } from "@/providers/notification-store-provider";
import { ProductsStoreProvider } from "@/providers/products-store-provider";
import { SurveyStoreProvider } from "@/providers/survey-store-provider";
import { LanguageProvider } from "@/context/LanguageProvider";

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: appName,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <LanguageProvider>
          <NotificationProvider>
            <NotificationStoreProvider>
              <ProductsStoreProvider>
                <SurveyStoreProvider>
                  {children}
                  <Toaster />
                </SurveyStoreProvider>
              </ProductsStoreProvider>
            </NotificationStoreProvider>
          </NotificationProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
