import Footer from "@/components/footer/Footer";
import SellerHeader from "@/components/sections/seller/header/SellerHeader";
import { getUserProfile } from "@/lib/api/profile/getProfile";
import { appName } from "@/lib/app-name";
import { ProfileStoreProvider } from "@/providers/profile-store-provider";

export const metadata = {
  title: appName + " | Seller",
  description: "Generated by create next app",
};

const SellerLayout = async ({ children }) => {
  const profile = await getUserProfile();

  return (
    <div className="flex w-full flex-col items-center">
      <ProfileStoreProvider profile={profile}>
        <SellerHeader />
        {children}
        <Footer />
      </ProfileStoreProvider>
    </div>
  );
};

export default SellerLayout;
