import Footer from "@/components/footer/Footer";
import SellerHeader from "@/components/sections/seller/header/SellerHeader";
import { appName } from "@/lib/app-name";

export const metadata = {
  title: appName + " | Seller",
  description: "Generated by create next app",
};

const SellerLayout = ({ children }) => {
  return (
    <div className="flex w-full flex-col items-center">
      <SellerHeader />
      {children}
      <Footer />
    </div>
  );
};

export default SellerLayout;
