import AdminHeader from "@/components/sections/admin/header/AdminHeader";
import AdminSidebar from "@/components/sections/admin/sidebar/AdminSidebar";
import { appName } from "@/lib/app-name";

export const metadata = {
  title: appName + " | Admin",
  description: "Generated by create next app",
};

const AdminDashboardLayout = ({ children }) => {
  return (
    <div className="grid h-screen w-full gap-3 overflow-hidden bg-[#ECF1F5] p-3 shadow-[3px_4px_25px_0px_#0000000D] md:grid-cols-[287px_1fr]">
      <div className="hidden h-full w-full md:flex">
        <AdminSidebar />
      </div>
      <div className="flex h-full w-full flex-col gap-3 overflow-auto">
        <AdminHeader />
        <div className="overflow-auto no-scrollbar px-2 flex flex-col h-full max-h-full">
          {children}
        </div>
      </div>
    </div>
  );
};

export default AdminDashboardLayout;
